CREATE TABLE demo_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO demo_users (name, email) VALUES ('Antigravity AI', 'ai@example.com');
INSERT INTO demo_users (name, email) VALUES ('Saidul Islam', 'saidul@example.com');
COMMIT;
EXIT;
