"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/Table";

// Audit log — application-level events, not stored in Oracle DB schema.
// These will be generated by backend middleware when DB operations are performed.
// Format: who did what to which entity, when.

type AuditEntry = {
  id: number;
  timestamp: string;
  severity: "Critical" | "Warning" | "Info";
  actor: string;
  actionType: string;
  targetEntity: string;
  details: string;
};

// Placeholder structure — will be populated by backend audit middleware
// when Oracle DB is connected and real operations begin.
const PLACEHOLDER_NOTE = "Audit logs will appear here once Oracle DB is connected and backend operations begin.";

export default function AuditPage() {
  const [logs] = useState<AuditEntry[]>([]);
  const [severityFilter, setSeverityFilter] = useState<"All" | "Critical" | "Warning" | "Info">("All");

  const filtered = severityFilter === "All" ? logs : logs.filter((l) => l.severity === severityFilter);

  const severityVariant = (s: string) =>
    s === "Critical" ? "danger" : s === "Warning" ? "warning" : "neutral";

  return (
    <div className="flex-1 overflow-y-auto p-4 lg:p-6 flex flex-col gap-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-headline-lg font-headline-lg text-on-surface">Audit Log</h1>
          <p className="text-body-md font-body-md text-on-surface-variant mt-1">
            System-level operation history — Backend middleware generated
          </p>
        </div>
        <Button variant="secondary" icon={<span className="material-symbols-outlined text-[18px]">download</span>}>
          Export Logs
        </Button>
      </div>

      {/* Severity filter */}
      <div className="flex gap-2">
        {(["All", "Critical", "Warning", "Info"] as const).map((s) => (
          <button
            key={s}
            onClick={() => setSeverityFilter(s)}
            className={`px-4 py-1.5 rounded-full text-label-caps font-label-caps transition-colors ${
              severityFilter === s
                ? "bg-primary text-on-primary"
                : "bg-surface-container text-on-surface-variant hover:bg-surface-container-high"
            }`}
          >
            {s}
          </button>
        ))}
      </div>

      {/* Info Banner */}
      <div className="bg-surface-container-low border border-primary/20 rounded-lg p-5 flex items-start gap-4">
        <span className="material-symbols-outlined text-primary text-[28px] shrink-0">database</span>
        <div>
          <p className="text-body-md font-body-md text-on-surface font-semibold mb-1">
            Waiting for Oracle DB connection
          </p>
          <p className="text-body-md font-body-md text-on-surface-variant">
            {PLACEHOLDER_NOTE}
          </p>
          <p className="text-label-caps font-label-caps text-on-surface-variant mt-2">
            Scope: INSERT, UPDATE, DELETE on DISASTER_EVENT, VICTIM, SHELTER, DONATION, DISTRIBUTION, PERSONNEL
          </p>
        </div>
      </div>

      {/* Audit Table */}
      <div className="bg-slate-surface border border-outline-variant rounded-xl overflow-hidden shadow-sm flex-1">
        <div className="p-4 border-b border-outline-variant flex items-center justify-between bg-surface-container">
          <h2 className="text-headline-md font-headline-md text-on-surface">
            {logs.length > 0 ? `${filtered.length} log entries` : "No log entries yet"}
          </h2>
          <div className="flex items-center gap-2 text-label-caps font-label-caps text-on-surface-variant">
            <span className="material-symbols-outlined text-[16px]">schedule</span>
            Live feed (post DB connection)
          </div>
        </div>
        <Table>
          <TableHeader className="bg-surface-container-low">
            <TableRow>
              <TableHead>Timestamp</TableHead>
              <TableHead>Severity</TableHead>
              <TableHead>Actor</TableHead>
              <TableHead>Action Type</TableHead>
              <TableHead>Target Entity</TableHead>
              <TableHead>Details</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-4 py-12 text-center">
                  <div className="flex flex-col items-center gap-3 text-on-surface-variant">
                    <span className="material-symbols-outlined text-[36px]">history</span>
                    <p className="text-body-md font-body-md">No audit entries yet</p>
                    <p className="text-label-caps font-label-caps text-on-surface-variant/70">
                      Entries will appear here as operations are performed via the system
                    </p>
                  </div>
                </td>
              </tr>
            ) : (
              filtered.map((log) => (
                <TableRow key={log.id} className="hover:bg-surface-container-high transition-colors">
                  <TableCell className="font-data-mono text-data-mono text-on-surface-variant">{log.timestamp}</TableCell>
                  <TableCell><Badge variant={severityVariant(log.severity) as any}>{log.severity}</Badge></TableCell>
                  <TableCell className="font-medium text-on-surface">{log.actor}</TableCell>
                  <TableCell className="font-data-mono text-data-mono text-warning-amber">{log.actionType}</TableCell>
                  <TableCell className="text-on-surface-variant">{log.targetEntity}</TableCell>
                  <TableCell className="text-on-surface-variant text-label-caps font-label-caps">{log.details}</TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
